[2024-10-07T03:26:02.010+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi_and_embeddings.embed_and_store_pdf_pages manual__2024-10-07T03:15:32.438113+00:00 [queued]>
[2024-10-07T03:26:02.024+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi_and_embeddings.embed_and_store_pdf_pages manual__2024-10-07T03:15:32.438113+00:00 [queued]>
[2024-10-07T03:26:02.024+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T03:26:02.025+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2024-10-07T03:26:02.025+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T03:26:02.043+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): embed_and_store_pdf_pages> on 2024-10-07 03:15:32.438113+00:00
[2024-10-07T03:26:02.048+0000] {standard_task_runner.py:55} INFO - Started process 993 to run task
[2024-10-07T03:26:02.050+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_with_pymupdf_and_convertapi_and_embeddings', 'embed_and_store_pdf_pages', 'manual__2024-10-07T03:15:32.438113+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/ETL-ConvertAPI.py', '--cfg-path', '/tmp/tmpm9f0wbaq']
[2024-10-07T03:26:02.051+0000] {standard_task_runner.py:83} INFO - Job 312: Subtask embed_and_store_pdf_pages
[2024-10-07T03:26:02.076+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-07T03:26:02.169+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi_and_embeddings.embed_and_store_pdf_pages manual__2024-10-07T03:15:32.438113+00:00 [running]> on host 1350c74cd1fb
[2024-10-07T03:26:02.294+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_with_pymupdf_and_convertapi_and_embeddings
AIRFLOW_CTX_TASK_ID=embed_and_store_pdf_pages
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T03:15:32.438113+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-07T03:15:32.438113+00:00
[2024-10-07T03:26:02.365+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL-ConvertAPI.py", line 189, in embed_and_store_pdf_pages
    raise ValueError(f"Missing extracted data paths for {pdf_key}")
ValueError: Missing extracted data paths for gaia/2023/test/021a5339-744f-42b7-bd9b-9368b3efda7a.pdf
[2024-10-07T03:26:02.388+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pdf_extraction_with_pymupdf_and_convertapi_and_embeddings, task_id=embed_and_store_pdf_pages, execution_date=20241007T031532, start_date=20241007T032602, end_date=20241007T032602
[2024-10-07T03:26:02.411+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 312 for task embed_and_store_pdf_pages (Missing extracted data paths for gaia/2023/test/021a5339-744f-42b7-bd9b-9368b3efda7a.pdf; 993)
[2024-10-07T03:26:02.423+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-07T03:26:02.455+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
