[2024-10-07T03:14:25.952+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi_and_embeddings.extract_with_pymupdf manual__2024-10-07T03:04:12.765296+00:00 [queued]>
[2024-10-07T03:14:25.964+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi_and_embeddings.extract_with_pymupdf manual__2024-10-07T03:04:12.765296+00:00 [queued]>
[2024-10-07T03:14:25.965+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T03:14:25.966+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2024-10-07T03:14:25.966+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T03:14:25.983+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_with_pymupdf> on 2024-10-07 03:04:12.765296+00:00
[2024-10-07T03:14:25.988+0000] {standard_task_runner.py:55} INFO - Started process 587 to run task
[2024-10-07T03:14:25.991+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_with_pymupdf_and_convertapi_and_embeddings', 'extract_with_pymupdf', 'manual__2024-10-07T03:04:12.765296+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/ETL-ConvertAPI.py', '--cfg-path', '/tmp/tmpywxllw7q']
[2024-10-07T03:14:25.991+0000] {standard_task_runner.py:83} INFO - Job 301: Subtask extract_with_pymupdf
[2024-10-07T03:14:26.020+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-07T03:14:26.121+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi_and_embeddings.extract_with_pymupdf manual__2024-10-07T03:04:12.765296+00:00 [running]> on host 1350c74cd1fb
[2024-10-07T03:14:26.255+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_with_pymupdf_and_convertapi_and_embeddings
AIRFLOW_CTX_TASK_ID=extract_with_pymupdf
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T03:04:12.765296+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-07T03:04:12.765296+00:00
[2024-10-07T03:14:26.292+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL-ConvertAPI.py", line 77, in extract_with_pymupdf
    tables = page.find_tables()
AttributeError: 'Page' object has no attribute 'find_tables'
[2024-10-07T03:14:26.318+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pdf_extraction_with_pymupdf_and_convertapi_and_embeddings, task_id=extract_with_pymupdf, execution_date=20241007T030412, start_date=20241007T031425, end_date=20241007T031426
[2024-10-07T03:14:26.348+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 301 for task extract_with_pymupdf ('Page' object has no attribute 'find_tables'; 587)
[2024-10-07T03:14:26.364+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-07T03:14:26.414+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
